workflows:
  ios-workflow:
    name: iOS Workflow (CocoaPods Fix)
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.oman.promo
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Get Flutter packages
        script: flutter pub get
      - name: Install pods (remove old lock, update repo, fresh install)
        script: |
          cd ios
          rm -f Podfile.lock
          pod repo update
          pod install --repo-update
      - name: Build iOS
        script: flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ios/**/*.app
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - hadeeraly165@gmail.com
        notify:
          success: true
          failure: true
